//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegradorTaller.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aula_equipamiento
    {
        public int id_aula { get; set; }
        public int id_equipamiento { get; set; }
        public string disponible { get; set; }
    
        public virtual aula aula { get; set; }
        public virtual equipamiento equipamiento { get; set; }
    }
}
