//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegradorTaller.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aula()
        {
            this.reserva = new HashSet<reserva>();
            this.equipamiento = new HashSet<equipamiento>();
            this.aula_equipamiento = new HashSet<aula_equipamiento>();
        }
    
        public int id_aula { get; set; }
        public string nombre { get; set; }
        public int capacidad { get; set; }
        public int id_ubicacion { get; set; }
        public int id_tipo { get; set; }
        public string activa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipamiento> equipamiento { get; set; }
        public virtual ubicacion ubicacion { get; set; }
        public virtual ubicacion ubicacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aula_equipamiento> aula_equipamiento { get; set; }
        public virtual tipoSala tipoSala { get; set; }
    }
}
