//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIntegradorTaller.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public respuesta()
        {
            this.detalles = new HashSet<detalles>();
        }
    
        public int id_respuesta { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> dni_vendedor { get; set; }
        public Nullable<System.DateTime> fecha_respuesta { get; set; }
        public string usuario_creacion { get; set; }
        public string respuesta1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles> detalles { get; set; }
        public virtual vendedor vendedor { get; set; }
    }
}
